src/od/flask/__init__.py
__all__=[
    # Subpackages

    # Modules
    'app',
    'views',

]

src/od/flask/app.py
from flask import Flask, render_template
from od.flask import views
from od.flask.datastore import ds


class FlaskApp:

    def __init__(self, host, port, domain, resource_dir, debug=False):
        self.host = host
        self.port = port
        self.domain = domain
        self.resource_dir = resource_dir

        app = Flask(__name__)
        app.config['DEBUG'] = debug
        self.register_errorhandlers(app)
        self.register_blueprints(app)
        self.register_extensions(app)
        self.app = app

    def register_errorhandlers(self, app):
        def render_error(error):
            """Render error template."""
            # If a HTTPException, pull the `code` attribute; default to 500
            error_code = getattr(error, "code", 500)
            return render_template(f'{error_code}.html', domain=self.domain), error_code

        for errcode in [404, 500]:
            app.errorhandler(errcode)(render_error)

    def register_blueprints(self, app):
        app.register_blueprint(views.blueprint)

    def register_extensions(self, app):
        ds.init_app(app, self.domain, self.resource_dir)

    def run(self):
        self.app.run(host=self.host, port=self.port)

src/od/flask/views.py
from flask import Blueprint, render_template, abort, send_from_directory
from od.flask.datastore import ds

blueprint = Blueprint('views', __name__)


@blueprint.route('/')
def index():
    _domain = ds.get().domain
    return render_template('views/index.html', domain=_domain)


@blueprint.route('/about')
def about():
    _domain = ds.get().domain
    return render_template('views/about.html', domain=_domain)


@blueprint.route('/domain/<string:name>')
def domain(name):
    _domain = ds.get().domain
    _subdomain = _domain.get_subdomain(name)
    if _subdomain is None:
        abort(404, '')
    return render_template('views/domain.html', domain=_domain, subdomain=_subdomain)


@blueprint.route('/boundedcontext/<string:name>')
def bounded_context(name):
    _domain = ds.get().domain
    _bc = _domain.get_bounded_context(name)
    if _bc is None:
        abort(404, '')
    return render_template('views/bounded_context.html', domain=_domain, bc=_bc)


@blueprint.route('/boundedcontext/<string:bounded_context_name>/model/<string:model_name>')
def model_object(bounded_context_name, model_name):
    _domain = ds.get().domain
    _bc = _domain.get_bounded_context(bounded_context_name)
    if _bc is None:
        abort(404, 'No such bounded context')
    _model = _bc.get_model_object(model_name)
    if _model is None:
        abort(404, 'No such model object')
    return render_template('views/model.html', domain=_domain, bc=_bc, model=_model)


@blueprint.route('/team/<string:name>')
def team(name):
    _domain = ds.get().domain
    _team = _domain.get_team(name)
    if _team is None:
        abort(404, '')
    return render_template('views/team.html', domain=_domain, team=_team)


@blueprint.route('/images/<path:filename>')
def image(filename):
    _resource_dir = ds.get().resource_dir
    return send_from_directory(_resource_dir, filename)


@blueprint.add_app_template_filter
def indefinite(phrase):
    if phrase:
        if phrase[0] in 'AEIOUaeiou':
            return f'an {phrase}'
        return f'a {phrase}'
    return ''

src/od/flask/templates/considerations.html
{% macro description(value, alternative='Consider adding a value') %}
    {% if value %}
        {% if value is iterable and value is not string %}
            {% for v in value %}
            <p>{{ v }}</p>
            {% endfor %}
        {% else %}
            <p>{{ value }}</p>
        {% endif %}
    {% else %}
        <p class="text-danger">{{ alternative }}</p>
    {% endif %}
{% endmacro %}

{% macro language(language, alternative='Consider adding language terms') %}
    {% if language %}
        <dl>
        {% for item in language %}
            <dt>{{ item.term }}</dt>
            <dd>{{ item.definition }}</dd>
        {% endfor %}
        </dl>
    {% else %}
        <p class="text-danger">{{ alternative }}</p>
    {% endif %}
{% endmacro %}

{% macro definition(concept, alternative='Consider adding a concept from the domain language') %}
    {% if concept %}
        <span>{{ concept.definition }}</span>
    {% else %}
        <span class="text-danger">Consider adding a concept from the domain language</span>
    {% endif %}
{% endmacro %}

src/od/flask/templates/footer.html
<footer>
    <small>
        <ul class="company">
            <li>© {{ domain.copyright }}</li>
            <li>(v. {{ domain.published_version }})</li>
        </ul>

        <ul class="footer-nav">
            <li><a href="{{ url_for('views.about') }}">About</a></li>
            <li><a href="mailto:{{ domain.contact_email }}">Contact</a></li>
        </ul>
    </small>
</footer>

src/od/flask/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="shortcut icon" href="{{url_for('static', filename='images/favicon.ico') }}">

    <title>{% block page_title %}Open Domain{% endblock %}</title>

    <meta
        name="description"
        content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="Jeff Bonevich" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/open-domain.css') }}">
    {% block css %}{% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">
    {% include "nav.html" %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
        {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<!--    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>-->
<!--    <script src="{{ url_for('static', filename='scripts/bootstrap/bootstrap.bundle.js') }}"></script>-->
    <script src="{{ url_for('static', filename='scripts/open-domain.js') }}"></script>

    {% block js %}{% endblock %}
</body>
</html>

src/od/flask/templates/modules.html
{% from "considerations.html" import definition %}

{% macro model_objects(header, models, show_concept=true) %}
{% if models %}
<div>
    <span class="fst-italic">{{ header }}</span>
    <ul>
        {% for item in models %}
        <li>
            <a href="{{ url_for('views.model_object', bounded_context_name=item.bounded_context.name, model_name=item.name) }}">{{ item.name }}</a>{% if show_concept %}: {{ definition(item.concept) }}{% endif %}
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}
{% endmacro %}

{% macro modules(modules) %}
<div class="accordion">
    {% for module in modules %}
    <div class="accordion-item">
        <h2 class="accordion-header" id="panelsStayOpen-heading-{{loop.index}}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse-{{loop.index}}" aria-expanded="true" aria-controls="panelsStayOpen-collapse-{{loop.index}}">{{ module.full_name }}</button>
        </h2>
        <div id="panelsStayOpen-collapse-{{loop.index}}" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-heading-{{loop.index}}">
            <div class="accordion-body">
                <div>
                    <p>
                        {% if module.concept %}
                        Model objects for <strong>{{ module.concept.term }}</strong>: {{ module.concept.definition }}
                        {% else %}
                        <span class="text-danger">Consider adding a concept from the domain language to this module</span>
                        {% endif %}
                    </p>
                </div>
                {{ model_objects('Sub-modules', module.modules) }}
                {{ model_objects('Entities', module.entities) }}
                {{ model_objects('Aggregates', module.aggregates) }}
                {{ model_objects('Domain Events', module.domain_events) }}
                {{ model_objects('Value Objects', module.value_objects) }}
                {{ model_objects('Domain Services', module.services) }}
                {{ model_objects('Factories', module.factories, false) }}
                {{ model_objects('Repositories', module.repositories, false) }}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endmacro %}

src/od/flask/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('views.index') }}">
            Open Domain
        </a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('views.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

src/od/flask/templates/views/about.html
{% extends "layout.html" %}

{% block page_title %}Open Domain: About{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-5">About</h1>
    <div class="row">
        <p class="lead">Domain Driven Design for {{ domain.name }}</p>
    </div>
</div>
{% endblock %}

src/od/flask/templates/views/bounded_context.html
{% extends "layout.html" %}

{% block content %}
{% from "considerations.html" import description %}
{% from "modules.html" import modules %}
<div class="container">
    <div class="row">
        <div>
            <h2>{{ bc.name }} Context</h2>
            <p>{{ bc.name }} is a bounded context within {{ domain.name }}.</p>

            <h4>Description</h4>
            {{ description(bc.description, 'Consider adding a description to the bounded context') }}

            <h4>Subdomain</h4>
            {% if bc.subdomains.has_multiple %}
                <p>This bounded context applies to the following domains <span class="text-danger">(Note: this is a violation; there ought to be only one subdomain per bounded context)</span>:</p>
                <ul>
                    {% for sub in bc.subdomains %}
                    <li><a href="{{ url_for('views.domain', name=sub.name) }}">{{ sub.name }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>This bounded context applies to the <a href="{{ url_for('views.domain', name=bc.subdomains.first.name) }}">{{ bc.subdomains.first.name }}</a> domain.</p>
            {% endif %}

            <h4>Team</h4>
            <p><a href="{{ url_for('views.team', name=bc.team.name) }}">{{ bc.team.name }}</a></p>

            <h4>Source Code</h4>
            <p><a href="{{ bc.scm_url }}" target="_blank" class="external-link">{{ bc.scm_url }}</a></p>

            <h4>Continuous Integration</h4>
            <p><a href="{{ bc.ci_url }}" target="_blank" class="external-link">{{ bc.ci_url }}</a></p>

            <h4>Relationships</h4>
            <div>
                <ul>
                    {% for rel in bc.relationships %}
                    {% set other_markup | safe %}

                    {% endset %}
                    <li>
                        {{ rel.description }}
                        <a href="{{url_for('views.bounded_context', name=rel.other_participant) }}">{{ rel.other_participant }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <h4>Modules</h4>
            {% if bc.modules %}
                {{ modules(bc.modules) }}
            {% else %}
                <p class="text-danger">Consider adding modules to this bounded context</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

src/od/flask/templates/views/domain.html
{% extends "layout.html" %}

{% block content %}
{% from "considerations.html" import description, language %}
<div class="container">
    <div class="row">
        <div>
            <h2>{{ subdomain.name }}</h2>
            <p>{{ subdomain.name }} is a <strong>{{ subdomain.classification }}</strong> subdomain of {{ domain.name }}.</p>

            <h4>Vision</h4>
            {{ description(subdomain.vision, 'Consider adding a vision statement for the domain') }}

            <h4>Description</h4>
            {{ description(subdomain.description, 'Consider adding a description') }}

            <h4>Domain Concepts</h4>
            {{ language(subdomain.domain_concepts, 'Consider adding domain concepts') }}
        </div>
    </div>
</div>
{% endblock %}

src/od/flask/templates/views/index.html
{% extends "layout.html" %}

{% block page_title %}Open Domain: {{ domain.name }}{% endblock %}

{% block content %}
{% from "considerations.html" import description %}
<div class="container">
    <div class="row">
        <div>
            <h2>{{ domain.name }}</h2>

            {{ description(domain.description, 'Consider adding a description') }}
        </div>
        <div>
            <h3>Subdomains</h3>
            <p class="od-linked-h5">
                <a href="{{ url_for('views.domain', name=domain.core_domain.name) }}">{{ domain.core_domain.name }} (Core)</a>
            </p>
            <p>
                {{ description(domain.core_domain.vision, 'Consider adding a vision statement for the subdomain') }}
            </p>

            {% for sub in domain.subdomains %}
            <p class="od-linked-h5">
                <a href="{{ url_for('views.domain', name=sub.name) }}">{{ sub.name }} ({{ sub.classification }})</a>
            </p>
            <p>
                {{ description(sub.vision, 'Consider adding a vision statement for the subdomain') }}
            </p>
            {% endfor %}

            {% if domain.core_domain_chart %}
            {% set chart = domain.core_domain_chart %}
            <div class="text-center">
                <figure class="figure">
                    <a href="{{ url_for('views.image', filename=chart.filename) }}" target="_blank">
                        <img src="{{ url_for('views.image', filename=chart.filename) }}"
                             style="width: {{ chart.width|default('100%') }}; height: {{ chart.height|default('auto') }};"
                             class="figure-img"
                        />
                    </a>
                    <figcaption class="figure-caption text-center">Core Domain Chart</figcaption>
                </figure>
            </div>
            {% endif %}
        </div>
        <div>
            <h3>Context Map</h3>
            {% for bc in domain.context_map.bounded_contexts %}
            <p class="od-linked-h5">
                <a href="{{ url_for('views.bounded_context', name=bc.name) }}">{{ bc.name }}</a>
            </p>
            {% endfor %}

            {% if domain.context_map.context_map_diagram %}
                {% set diagram = domain.context_map.context_map_diagram %}
            <div class="text-center">
                <figure class="figure">
                    <a href="{{ url_for('views.image', filename=diagram.filename) }}" target="_blank">
                        <img src="{{ url_for('views.image', filename=diagram.filename) }}"
                             style="width: {{ diagram.width|default('100%') }}; height: {{ diagram.height|default('auto') }};"
                             class="figure-img"
                        />
                    </a>
                    <figcaption class="figure-caption text-center">Context Map Diagram</figcaption>
                </figure>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

src/od/flask/templates/views/model.html
{% extends "layout.html" %}

{% block content %}
{% from "considerations.html" import description, definition %}
{% from "modules.html" import modules, model_objects %}
<div class="container">
    <div class="row">
        <div>
            <h2>{{ model.name }}</h2>
            <p>
                {{ model.name }} is {{ model.type|indefinite }} model object within the
                <a href="{{ url_for('views.bounded_context', name=bc.name) }}">{{ bc.name }}</a> bounded context.
            </p>

            <h4>Description</h4>
            {{ description(model.description, 'Consider adding a description to the model object') }}

            {% if model.module %}
            <h4>Module</h4>
            <p>
                <a href="{{ url_for('views.model_object', bounded_context_name=bc.name, model_name=model.module.name) }}">
                    {{ model.module.full_name }}
                </a>
            </p>
            {% endif %}

            {% if model.type == 'Module' %}
                <h4>Model Objects</h4>
                {{ model_objects('Entities', model.entities) }}
                {{ model_objects('Aggregates', model.aggregates) }}
                {{ model_objects('Domain Events', model.domain_events) }}
                {{ model_objects('Value Objects', model.value_objects) }}
                {{ model_objects('Domain Services', model.services) }}
                {{ model_objects('Factories', model.factories, false) }}
                {{ model_objects('Repositories', model.repositories, false) }}

                {% if model.modules %}
                <h4>Sub-modules</h4>
                {{ modules(model.modules) }}
                {% endif %}
            {% elif model.supports_attributes %}
                <h4>Attributes</h4>
                <ul>
                    {% if model.type == 'Entity' %}
                        {% if model.id %}
                        <li><strong>{{ model.id.name}}</strong> ({{ model.id.type }}; identifier)</li>
                        {% else %}
                        <li><span class="text-danger">Requires an identifier</span></li>
                        {% endif %}
                    {% endif %}

                    {% for attr in model.attributes %}
                    <li><em>{{ attr.name }}</em> ({{ attr.type }})</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

src/od/flask/templates/views/team.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div>
            <h2>Team {{ team.name }}</h2>
            <h4>Product Owner</h4>
            <p><a href="mailto:{{ team.contact }}">{{ team.product_owner }}</a></p>
            <h4>Team Website</h4>
            <p><a href="{{ team.website }}" target="_blank" class="external-link">{{ team.website }}</a></p>
        </div>
    </div>
</div>
{% endblock %}